services:
  webserver:
    volumes:
      - nfse_data:/usr/local/airflow/data

  scheduler:
    volumes:
      - nfse_data:/usr/local/airflow/data

  triggerer:
    volumes:
      - nfse_data:/usr/local/airflow/data

volumes:
  nfse_data:
